# Generated by Django 3.1.1 on 2020-10-22 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(default=' ', max_length=30, verbose_name='CATEGORIZACIÓN')),
            ],
            options={
                'verbose_name': 'CATEGORIA',
                'verbose_name_plural': 'CATEGORIAS DE EQUIPOS',
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=50, verbose_name='NUMERO DE SERIE')),
                ('nombre_equipo', models.CharField(max_length=40, verbose_name='NOMBRE DEL EQUIPO')),
                ('marca_equipo', models.CharField(blank=True, max_length=40, null=True, verbose_name='MARCA DEL EQUIPO')),
                ('modelo_equipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='MODELO DEL EQUIPO')),
                ('anio_fabricacion', models.DateField(blank=True, null=True, verbose_name='AÑO DE FABRICACIÓN')),
                ('fecha_recepcion_abast', models.DateField(blank=True, null=True, verbose_name='FECHA DE RECEPCIÓN EN ABASTECIMIENTO')),
                ('fecha_recepcion_sc', models.DateField(blank=True, null=True, verbose_name='FECHA DE INSTALACIÓN EN SERVICIO CLÍNICO')),
                ('frecuencia_mantencion', models.IntegerField(blank=True, null=True, verbose_name='FRECUENCIA DE MANTENCIÓN')),
                ('categoria_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.categoria', verbose_name='CATEGORÍA')),
            ],
            options={
                'verbose_name': 'EQUIPOS MEDICOS',
                'verbose_name_plural': 'EQUIPOS MEDICOS',
                'ordering': ['nombre_equipo'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_equipo', models.CharField(max_length=30, verbose_name='ESTADO')),
            ],
            options={
                'verbose_name': 'ESTADO',
                'verbose_name_plural': 'ESTADOS DE EQUIPOS',
            },
        ),
        migrations.CreateModel(
            name='EstadoMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=40, verbose_name='ESTADO MP')),
            ],
            options={
                'verbose_name': 'ESTADO MP',
                'verbose_name_plural': 'ESTADOS MP',
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=40, verbose_name='NOMBRE PROVEEDOR')),
                ('tecnico_representante', models.CharField(blank=True, max_length=60, null=True, verbose_name='TECNICO REPRESENTANTE')),
                ('telefono_proveedor', models.CharField(blank=True, max_length=30, null=True, verbose_name='TELEFONO PROVEEDOR')),
                ('email_proveedor', models.EmailField(blank=True, max_length=40, null=True, verbose_name='EMAIL PROVEEDOR')),
                ('fecha_vencimiento_contrato', models.DateField(blank=True, null=True, verbose_name='FECHA VENCIMIENTO DE CONTRATO')),
                ('direccion_proveedor', models.CharField(blank=True, max_length=50, null=True, verbose_name='DIRECCION PROVEEDOR')),
            ],
            options={
                'verbose_name': 'PROVEEDORES',
                'verbose_name_plural': 'PROVEEDORES',
                'ordering': ['nombre_proveedor'],
            },
        ),
        migrations.CreateModel(
            name='ServiciosClinicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=40, verbose_name='UNIDAD')),
                ('responsablesc', models.CharField(blank=True, max_length=40, null=True, verbose_name='RESPONSABLE')),
                ('rut_responsablesc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT RESPONSABLE')),
                ('email_responsablesc', models.EmailField(blank=True, max_length=40, null=True, verbose_name='EMAIL RESPONSABLE')),
                ('telefono_responsablesc', models.CharField(blank=True, max_length=20, null=True, verbose_name='TELEFONO RESPONSABLE')),
            ],
            options={
                'verbose_name': 'SERVICIOS CLINICOS',
                'verbose_name_plural': 'SERVICIOS CLINICOS',
                'ordering': ['unidad'],
            },
        ),
        migrations.CreateModel(
            name='MantencionesProgramadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField(verbose_name='FECHA PROGRAMADA')),
                ('estado_mp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp.estadomp', verbose_name='ESTADO')),
                ('numero_serie_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.equipos', verbose_name='EQUIPO')),
                ('proveedor_mantencion_programada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.proveedores', verbose_name='PROVEEDOR ADJUDICADO')),
            ],
            options={
                'verbose_name': 'MANTENCIONES PROGRAMADAS',
                'verbose_name_plural': 'MANTENCIONES PROGRAMADAS',
            },
        ),
        migrations.CreateModel(
            name='MantencionesPreventivasRealizadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_trabajo_mp', models.CharField(max_length=50, unique=True, verbose_name='ORDEN DE TRABAJO MP')),
                ('fecha_mp', models.DateField(blank=True, null=True, verbose_name='FECHA REALIZACION MP')),
                ('copia_digital_mp', models.FileField(blank=True, null=True, upload_to='', verbose_name='COPIA DIGITAL OT')),
                ('carta_reprogramacion', models.FileField(blank=True, null=True, upload_to='', verbose_name='CARTA REPROGRAMACIÓN')),
                ('carta_retiro', models.FileField(blank=True, null=True, upload_to='', verbose_name='CARTA DE RETIRO DEL SERVICIO')),
                ('observaciones_mp', models.CharField(blank=True, max_length=500, null=True, verbose_name='OBSERVACIONES')),
                ('id_mantencion_programada', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp.mantencionesprogramadas')),
                ('proveedor_mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.proveedores')),
            ],
            options={
                'verbose_name': 'MANTENCIONES PREVENTIVAS REALIZADAS',
                'verbose_name_plural': 'MANTENCIONES PREVENTIVAS REALIZADAS',
            },
        ),
        migrations.CreateModel(
            name='MantencionesCorrectivas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_trabajo_mc', models.CharField(max_length=50, unique=True, verbose_name='ORDEN DE TRABAJO MC')),
                ('fecha_mc', models.DateField(blank=True, null=True, verbose_name='FECHA REALIZACION MC')),
                ('copia_digital_mc', models.FileField(blank=True, null=True, upload_to='', verbose_name='COPIA DIGITAL OT')),
                ('observaciones_mc', models.CharField(blank=True, max_length=500, null=True, verbose_name='OBSERVACIONES')),
                ('proveedor_mc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.proveedores')),
                ('serie_equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.equipos')),
            ],
            options={
                'verbose_name': 'MANTENCIONES CORRECTIVAS',
                'verbose_name_plural': 'MANTENCIONES CORRECTIVAS',
            },
        ),
        migrations.AddField(
            model_name='equipos',
            name='estado_del_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.estado', verbose_name='ESTADO'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='proveedor_del_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.proveedores', verbose_name='PROVEEDOR'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='serv_clinico_equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.serviciosclinicos', verbose_name='SERVICIO CLÍNICO'),
        ),
    ]
